apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: cloudsearch
  name: cloudsearch-view
rules:
- apiGroups: [""]
  resources: ["services", "endpoints", "pods", "configmaps", "secrets", "serviceaccounts"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions", "apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions", "batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings", "clusterroles"]
  verbs: ["get", "list", "watch"]