apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: example-psp
  namespace: kube-system
rules:
- apiGroups:
  - policy
  resourceNames:
  - example
  resources:
  - podsecuritypolicies
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: example-psp
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: example-psp
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  apiGroup: rbac.authorization.k8s.io
  name: system:serviceaccounts
---