apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "k8s-user.fullname" . }}
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects: #todo loop though all SAs
- kind: ServiceAccount
  name: service-search-service  #todo loop though all SAs
  namespace: {{ .Values.namespace }}  #todo loop though all SAs from values
- kind: ServiceAccount
  name: service-commerce-search-service
  namespace: {{ .Values.namespace }}
