apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "k8s-user.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "k8s-user.fullname" $ }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects: #todo loop though all SAs
{{- if .Values.serviceAccounts }}
{{- range $i, $var := .Values.serviceAccounts }}
- kind: ServiceAccount
  name: service-search-service  #todo loop though all SAs
  namespace: {{ .Values.namespace }}  #todo loop though all SAs from values
{{- end }}
{{- end }}
