apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-edit-role
  namespace: kiwis
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: service-search-service
  namespace: kiwis
- kind: ServiceAccount
  name: service-commerce-search-service
  namespace: kiwis
